### ISSUE TITLE
Does your engine also support radio-buttons ?

### ISSUE THREAD

**Issue by StefH** [crpietschmann/jsQuizEngine#5]
In your example exam (Azure-70-532-Practice-Test) a lot of questions should have only 1 answer, but still check-boxes are displayed instead of radio-buttons. Is this intentional or does the engine not support radio-buttons?

**Comment by crpietschmann** [comment]
This is something that surely needs to be fixed. Thanks for bringing it up. 👍

**Comment by crpietschmann** [comment]
This has been implemented so questions with multiple correct answers will get radio buttons, and questions with only a single correct answer will get checkboxes.

**Comment by StefH** [comment]
Very cool ! Thanks.
